
package com.thomsonreuters.wokmws.cxf.woksearchlite;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WokSearchLite", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WokSearchLite {


    /**
     * 
     * @param uids
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults
     * @throws InternalServerException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveById", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveById")
    @ResponseWrapper(localName = "retrieveByIdResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveByIdResponse")
    public SearchResults retrieveById(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uids", targetNamespace = "")
        List<String> uids,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param retrieveParameters
     * @param queryId
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults
     * @throws InternalServerException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveResponse")
    public SearchResults retrieve(
        @WebParam(name = "queryId", targetNamespace = "")
        String queryId,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param queryParameters
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults
     * @throws InternalServerException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResponse")
    public SearchResults search(
        @WebParam(name = "queryParameters", targetNamespace = "")
        QueryParameters queryParameters,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param editionDesc
     * @param timeSpan
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults
     * @throws InternalServerException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "citingArticles", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.CitingArticles")
    @ResponseWrapper(localName = "citingArticlesResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.CitingArticlesResponse")
    public SearchResults citingArticles(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        String uid,
        @WebParam(name = "editionDesc", targetNamespace = "")
        List<EditionDesc> editionDesc,
        @WebParam(name = "timeSpan", targetNamespace = "")
        TimeSpan timeSpan,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param editionDesc
     * @param timeSpan
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults
     * @throws InternalServerException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "relatedRecords", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RelatedRecords")
    @ResponseWrapper(localName = "relatedRecordsResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RelatedRecordsResponse")
    public SearchResults relatedRecords(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        String uid,
        @WebParam(name = "editionDesc", targetNamespace = "")
        List<EditionDesc> editionDesc,
        @WebParam(name = "timeSpan", targetNamespace = "")
        TimeSpan timeSpan,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

}
