
package com.thomsonreuters.wokmws.cxf.woksearch;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WokSearch", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WokSearch {


    /**
     * 
     * @param retrieveParameters
     * @param queryId
     * @return
     *     returns java.util.List<com.thomsonreuters.wokmws.cxf.woksearch.CitedReference>
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InvalidInputException_Exception
     * @throws ESTIWSException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "citedReferencesRetrieve", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.CitedReferencesRetrieve")
    @ResponseWrapper(localName = "citedReferencesRetrieveResponse", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.CitedReferencesRetrieveResponse")
    public List<CitedReference> citedReferencesRetrieve(
        @WebParam(name = "queryId", targetNamespace = "")
        String queryId,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param editions
     * @param timeSpan
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InvalidInputException_Exception
     * @throws ESTIWSException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "relatedRecords", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.RelatedRecords")
    @ResponseWrapper(localName = "relatedRecordsResponse", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.RelatedRecordsResponse")
    public FullRecordSearchResults relatedRecords(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        String uid,
        @WebParam(name = "editions", targetNamespace = "")
        List<EditionDesc> editions,
        @WebParam(name = "timeSpan", targetNamespace = "")
        TimeSpan timeSpan,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param editions
     * @param timeSpan
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearch.CitedReferencesSearchResults
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InvalidInputException_Exception
     * @throws ESTIWSException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "citedReferences", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.CitedReferences")
    @ResponseWrapper(localName = "citedReferencesResponse", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.CitedReferencesResponse")
    public CitedReferencesSearchResults citedReferences(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        String uid,
        @WebParam(name = "editions", targetNamespace = "")
        List<EditionDesc> editions,
        @WebParam(name = "timeSpan", targetNamespace = "")
        TimeSpan timeSpan,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param retrieveParameters
     * @param queryId
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearch.FullRecordData
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws InvalidInputException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.RetrieveResponse")
    public FullRecordData retrieve(
        @WebParam(name = "queryId", targetNamespace = "")
        String queryId,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param queryParameters
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InvalidInputException_Exception
     * @throws ESTIWSException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.SearchResponse")
    public FullRecordSearchResults search(
        @WebParam(name = "queryParameters", targetNamespace = "")
        QueryParameters queryParameters,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param editions
     * @param timeSpan
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws InvalidInputException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "citingArticles", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.CitingArticles")
    @ResponseWrapper(localName = "citingArticlesResponse", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.CitingArticlesResponse")
    public FullRecordSearchResults citingArticles(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        String uid,
        @WebParam(name = "editions", targetNamespace = "")
        List<EditionDesc> editions,
        @WebParam(name = "timeSpan", targetNamespace = "")
        TimeSpan timeSpan,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uids
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.cxf.woksearch.FullRecordSearchResults
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InvalidInputException_Exception
     * @throws ESTIWSException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveById", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.RetrieveById")
    @ResponseWrapper(localName = "retrieveByIdResponse", targetNamespace = "http://woksearch.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearch.RetrieveByIdResponse")
    public FullRecordSearchResults retrieveById(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uids", targetNamespace = "")
        List<String> uids,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

}
